_BASE_: "Base-DensePose-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  ROI_DENSEPOSE_HEAD:
    DECODER_ON: False
    PREDICTOR_NAME: "PoiseNetPredictor"
    LOSS_NAME: "DensePosePoiseNetLoss"
    PART_WEIGHTS: 0.001
  POISENET:
    BLOCK_FPATH: "/home/sunjunyao/code/Model/tmp/blocks/block-5.json"
    BLOCK_NUM: 5
    PART_LOSS_TYPE: "AEQL"
    FREQ_CLASSES: [7,8,11,12]
    POISE_CLS_WEIGHTS: 0.0008
    POISE_REGRESSION_WEIGHTS: 0.01
SEED: 35409553
SOLVER:
  MAX_ITER: 130000
  STEPS: (100000, 120000)
OUTPUT_DIR: "./output/poisenet_R_50_s1x_8gpu_aeql-norm-8-0.001_sabl-0.08+1_35409553/"